/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zbao_news_FlashActivity */

#ifndef _Included_com_zbao_news_FlashActivity
#define _Included_com_zbao_news_FlashActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zbao_news_FlashActivity
 * Method:    getUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zbao_news_FlashActivity_getUrl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
