package com.zbao.news.greendao.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.zbao.news.greendao.entity.Patient;

import com.zbao.news.greendao.entity.Patient;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PATIENT".
*/
public class PatientDao extends AbstractDao<Patient, Long> {

    public static final String TABLENAME = "PATIENT";

    /**
     * Properties of entity Patient.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PATIENT_ID = new Property(1, String.class, "PATIENT_ID", false, "PATIENT__ID");
        public final static Property PARENT_DOCTOR_ID = new Property(2, String.class, "PARENT_DOCTOR_ID", false, "PARENT__DOCTOR__ID");
        public final static Property SUPER_DOCTOR_ID = new Property(3, String.class, "SUPER_DOCTOR_ID", false, "SUPER__DOCTOR__ID");
        public final static Property Primary_id = new Property(4, Long.class, "primary_id", false, "PRIMARY_ID");
    };

    private DaoSession daoSession;


    public PatientDao(DaoConfig config) {
        super(config);
    }
    
    public PatientDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PATIENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PATIENT__ID\" TEXT," + // 1: PATIENT_ID
                "\"PARENT__DOCTOR__ID\" TEXT," + // 2: PARENT_DOCTOR_ID
                "\"SUPER__DOCTOR__ID\" TEXT," + // 3: SUPER_DOCTOR_ID
                "\"PRIMARY_ID\" INTEGER);"); // 4: primary_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PATIENT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Patient entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String PATIENT_ID = entity.getPATIENT_ID();
        if (PATIENT_ID != null) {
            stmt.bindString(2, PATIENT_ID);
        }
 
        String PARENT_DOCTOR_ID = entity.getPARENT_DOCTOR_ID();
        if (PARENT_DOCTOR_ID != null) {
            stmt.bindString(3, PARENT_DOCTOR_ID);
        }
 
        String SUPER_DOCTOR_ID = entity.getSUPER_DOCTOR_ID();
        if (SUPER_DOCTOR_ID != null) {
            stmt.bindString(4, SUPER_DOCTOR_ID);
        }
 
        Long primary_id = entity.getPrimary_id();
        if (primary_id != null) {
            stmt.bindLong(5, primary_id);
        }
    }

    @Override
    protected void attachEntity(Patient entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Patient readEntity(Cursor cursor, int offset) {
        Patient entity = new Patient( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // PATIENT_ID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // PARENT_DOCTOR_ID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // SUPER_DOCTOR_ID
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // primary_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Patient entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPATIENT_ID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPARENT_DOCTOR_ID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSUPER_DOCTOR_ID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPrimary_id(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Patient entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Patient entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPatientDao().getAllColumns());
            builder.append(" FROM PATIENT T");
            builder.append(" LEFT JOIN PATIENT T0 ON T.\"PRIMARY_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Patient loadCurrentDeep(Cursor cursor, boolean lock) {
        Patient entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Patient patient = loadCurrentOther(daoSession.getPatientDao(), cursor, offset);
        entity.setPatient(patient);

        return entity;    
    }

    public Patient loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Patient> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Patient> list = new ArrayList<Patient>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Patient> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Patient> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
